### ISSUE TITLE
Tutorial isn't working for me

### ISSUE THREAD

**Issue by rdtechie** [getoutreach/stencil#212]
When I'm trying to execute the instructions here: https://engineering.outreach.io/stencil/getting-started/quick-start/#step-3-import-a-module I am receiving this error:

`failed to run: run codegen: failed to render template "github.com/getoutreach/stencil-base/.github/CODEOWNERS.tpl": template: github.com/getoutreach/stencil-base/.github/CODEOWNERS.tpl:2:25: executing "github.com/getoutreach/stencil-base/.github/CODEOWNERS.tpl" at <stencil.Arg>: error calling Arg: module "github.com/getoutreach/stencil-base" requires argument "reportingTeam" but is not set`

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/6579452/220263796-6b7e34f6-bab0-41e4-8a77-b86f07696387.png">

**Comment by jaredallard** [comment]
Will work on updating the documentation, for now should be able to get past this by setting `reportingTeam` in your `service.yaml`. Example:

```yaml
arguments:
  reportingTeam: im-not-a-real-team
````

**Comment by jaredallard** [comment]
There's another issue if you work around that, I'm about 80% done with the fix for it. Just a little delayed right now!

**Comment by rdtechie** [comment]
Not working for me:

`service.yaml`
```yaml
name: helloworld
arguments:
  reportingTeam: im-not-a-real-team
description: "My awesome service!"
modules:
  - name: github.com/getoutreach/stencil-base
```

Message:
```shell
➜  helloworld stencil
INFO[0000] stencil v1.30.0
INFO[0000] Fetching dependencies
INFO[0003]  -> github.com/getoutreach/stencil-base v0.8.0
INFO[0003]  -> github.com/getoutreach/devbase v2.9.2
INFO[0003] Loading native extensions
INFO[0003] Rendering templates
ERRO[0003] failed to run: run codegen: failed to render template "github.com/getoutreach/stencil-base/README.md.tpl": template: github.com/getoutreach/stencil-base/README.md.tpl:14:65: executing "github.com/getoutreach/stencil-base/README.md.tpl" at <.Runtime.Box.Org>: nil pointer evaluating *box.Config.Org
```

**Comment by jaredallard** [comment]
@rdtechie We are releasing the fix to that today! Thanks for your patience!

**Comment by jaredallard** [comment]
Should be fixed in `v1.31.0`

**Comment by rdtechie** [comment]
Still not working:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/6579452/222697373-5d7c22bf-cfb1-41fe-bc14-9e5cdf1f9fb4.png">

Modified `service.yaml` to this:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/6579452/222697578-4c358be7-d7b3-4b2b-8ce9-54bb049fe1e4.png">

Then got the next error:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/6579452/222697740-5b0eb3ac-fdff-45e2-bbf9-8337cbc47c1b.png">

**Comment by jaredallard** [comment]
Will update the docs for the required argument (`description`). Looks like we need to note that `python-yq` is required for `devbase` to be pulled in, will also update the docs there. If you're on macOS, you can run `brew install python-yq` for that, otherwise `pip install python-yq` (taking care to ensure it is in your path) can be used.

**Comment by rdtechie** [comment]
Closing this issue as this project isn't looking promising to the open source community.
